[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "Buttonless"
dynamic_title = true
option_as_alt = "Both"
#startup_mode = "Maximized"
#opacity = 0.9
blur = true

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 10
y = 10

[general]

live_config_reload = true

import = [
  "~/.config/alacritty/themes/tokyo-night.toml"
]

[terminal]
